---
title: "ALS with P3"
author: "Yuqiao Liu, Hanbo Jiao"
output: html_notebook
---


```{r}
library(parallel)
library(tidyverse)
source("../lib/ALSwithP3.R")
```

# Data used for test
```{r}
data <- read.csv("../data/ml-latest-small/ratings.csv")
set.seed(1)

# train-test split (.8/.2)
train_ind <- createDataPartition(data$userId, p=.8, list=F)

train <- data[train_ind, ]
test <- data[-train_ind, ]
```


# Load cross-validation Func
```{r}
source("../lib/cross_validation.R")
```
# Paramter tuning for ALS_krr
```{r}
fs <- c(5, 10, 15)
lambdas_als <- c(1, 5,10)
lambdas_P <- c(1, 5, 10)
sigmas <- c(1,2,3)

cv.df <- expand.grid("fs"=fs, 
                     "lambdas_als"=lambdas_als, 
                     "lambdas_p"=lambdas_P, 
                     "sigmas" =sigmas)
```

```{r, eval=FALSE}
cl <- makeCluster(detectCores())

x=cv.df %>%
  as_tibble() %>%
  mutate(train_mean=NA,test_mean=NA)

for (i in 1:dim(x)[1]){
  tmp <- cv.functionYQ(dat_train=data,
                       K=5,
                       f=x[i,]$fs,
                       maxIter=15,
                       lambdas_als=x[i,]$lambdas_als,
                       lambdas_p=x[i,]$lambdas_p,
                       sigmas=x[i,]$sigmas)
  
  x[i,"train_mean"]=tmp$mean_train_rmse
  x[i,"test_mean"]=tmp$mean_test_rmse

  rm(tmp)
}
save(x, file="../output/cvtmp.RData")

stopCluster(cl)
```

# Choosing Paramters for als with krr
```{r}
load(x, file="../output/cvtmp.RData")
```

# Result of Funciton of ALS and KRR
```{r, message=FALSE}
cl <- makeCluster(detectCores())

# alsP3Result <- ALS_KRR(data, train, test, f=, maxIters=, lambda_als=, lambda_p=, sigma=)

stopCluster(cl)
```

