---
title: "A3 + R1 + R3 + P3"
author: "Jinxu Xiang"
output: 
 html_notebook
 pdf_document
---

```{r, include = F}
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(cache = T)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
options(mc.cores = parallel::detectCores())
library(tidyverse)
library(ggplot2)
library(anytime)
library(caret)
library(parallel)
```

### Data

```{r}
data <- read.csv("../data/ml-latest-small/ratings.csv")

data$timestamp <- anydate(data$timestamp)
data <- data %>% 
  group_by(userId) %>% 
  mutate(timediff = (timestamp - mean(timestamp)) %>% as.numeric) %>% 
  ungroup() %>%
  arrange(timestamp)

set.seed(1)

# train-test split (.8/.2)
train_ind <- createDataPartition(data$userId, p=.8, list=F)


data_train <- data[train_ind, ]
data_test <- data[-train_ind, ]
```

### RMSE

```{r}
RMSE <- function(rating, est_rating){
  sqr_err <- function(id){
    sqr_error <- (as.numeric(rating[id,3]) - est_rating[as.character(rating[id,1]), as.character(rating[id,2])])^2
    return(sqr_error)
  }
  error = sapply(1:nrow(rating), sqr_err)
  return(sqrt(mean(error)))  
}
```

### Change function

```{r}
findSolve <- function(id, solveBy, train, lambda, user_mat, movie_mat, au, bu, bi, mu, f){
  id <- as.integer(id)
  # Fix Movies, solve User
  if(solveBy == "Movies"){
    # find all the users who rate movie i
    U_set <- as.character(train[train$movieId == id,]$userId)
    dev <- train[train$movieId == id,]$dev
    user_mat_p = user_mat[,U_set]
    Result = solve(user_mat_p %*% t(user_mat_p) + lambda* diag(f+1)) %*% user_mat_p %*% (train[train$movieId == id,]$rating - mu - bu[,U_set] - au[,U_set]*dev)
    return(Result)
  }
  
  # Fix User, solve Movie
  else if(solveBy == "Users"){
    # find all the moives rated by user u
    M_set <- as.character(train[train$userId == id,]$movieId)
    x <- train[train$userId == id,]$rating
    dev <- train[train$userId == id,]$dev
    R <- matrix(x, ncol = length(x), nrow = 1)
    
    cname <- colnames(movie_mat[,M_set])
    movie_mat_p <- rbind(dev, movie_mat[,M_set])
    colnames(movie_mat_p) <- cname

    Result = solve(movie_mat_p %*% t(movie_mat_p) + lambda * diag(f+2)) %*% movie_mat_p %*% t(R - mu - bi[,M_set])
    return(Result)
  }
  else return("Please let matSolv be in right way")
}

```

### ALS R1 + R3

```{r}
ALS.R1R3 <- function(f = 10, lambda = 5, beta = 0.4, maxIters = 5, data = data,
            train = data_train, test = data_test){
  
  train = train %>% mutate(dev = ifelse(timediff>0, 1, -1)*abs(timediff)^beta)
  test = test %>% mutate(dev = ifelse(timediff>0, 1, -1)*abs(timediff)^beta)
  all_data = rbind(train, test)
  
  # Factorized the Movies and User matrices
  UserId <- levels(as.factor(data$userId))
  U <- length(UserId)
  
  MovieId <- levels(as.factor(data$movieId))
  M <- length(MovieId)

  avgRatingByUser <- data %>% 
    group_by(userId) %>% 
    summarise(avgRating = mean(rating))
  
  avgRatingByMovie <- data %>% 
    group_by(movieId) %>% 
    summarise(avgRating = mean(rating))
  
  Users <- matrix(c(avgRatingByUser$avgRating, runif((f-1)*U, -10, 10)), nrow=f)
  colnames(Users) <- UserId
  
  Movies <- matrix(c(avgRatingByMovie$avgRating, rnorm((f-1)*M, -10, 10)), nrow=f)
  colnames(Movies) <- MovieId
  
  bu <- matrix(rep(0, U), ncol = U)
  colnames(bu) <- UserId
  
  bi <- matrix(rep(0, M), ncol = M)
  colnames(bi) <- MovieId
  
  R <- matrix(rep(0, U*M), ncol = M)
  colnames(R) <- MovieId
  
  au <- matrix(rep(0, U), ncol = U)
  colnames(au) <- UserId
  
  # mean of all the ratings in train data set.
  Ave_rating <- mean(train$rating)
  
  trainRMSE <- rep(NA, maxIters)
  testRMSE <- rep(NA, maxIters)
  
  
  clusterExport(cl, "findSolve", envir = environment())
  clusterExport(cl, "f", envir = environment())
  clusterExport(cl, "UserId", envir = environment())
  clusterExport(cl, "MovieId", envir = environment())
  
  iter <- 1
  while(iter <= maxIters){
    S = Sys.time()
    
    Movies_cal <- rbind(rep(1,M), Movies)
    colnames(Movies_cal) <- MovieId
    Users_cal <- rbind(au, bu, Users)
    
    # Fix Movie, solve User
    Users_cal <- parSapply(cl, as.character(UserId), findSolve, solveBy = "Users", train = train, lambda = lambda, user_mat = Users_cal, movie_mat = Movies_cal, au = au, bu = bu, bi = bi, mu = Ave_rating, f = f, USE.NAMES = T)
    
    # Update au, bu and Users
    au[1,] <- Users_cal[1, ]
    bu[1,] <- Users_cal[2, ]
    Users <- Users_cal[-c(1,2), ]

    Users_cal <- rbind(rep(1,U), Users)
    colnames(Users_cal) <- UserId
    Movies_cal <- rbind(bi, Movies)
    
    # Fix User, solve Movie

    Movies_cal <- parSapply(cl, as.character(MovieId), findSolve, solveBy = "Movies", train = train, lambda = lambda, user_mat = Users_cal, movie_mat = Movies_cal, au = au, bu = bu, bi = bi, mu = Ave_rating, f = f, USE.NAMES = T)
    
    # Update bi and Movies
    bi[1,] <- Movies_cal[1,]
    Movies <- Movies_cal[-1,]
    
    # Rating Matrix
    mat <- t(Users) %*% Movies
    
    bu_ui <- matrix(rep(NA, U*M), ncol = M)
    for (i in 1:M) {
      bu_ui[,i] <- t(bu)
    }
    
    bi_ui <- matrix(rep(NA, U*M), ncol = M)
    for (u in 1:U) {
      bi_ui[u, ] <- bi
    }
    
    au_mat <- matrix(rep(au,I),nrow=U,byrow = F)
    dev_mat <- all_data %>%
      unique() %>%
      select(userId, movieId, dev) %>%
      arrange(userId, movieId) %>%
      pivot_wider(userId, names_from = movieId, values_from = dev, values_fill = list(dev = 0)) %>%
      select(-1)
    colnames(dev_mat) <- colnames(dev_mat) %>% as.numeric()
    dev_mat <- dev_mat %>% select(as.character(MovieId))
    au_dev_ui <- au_mat*dev_mat

    au_dev_ui <- as.matrix(au_dev_ui)
    
    mu_ui <- matrix(rep(mu, U*I), ncol = I)
    
    R <- mat + mu_ui + bu_ui + bi_ui + au_dev_ui
    
    # RMSE 
    est_rating <- as.matrix(R)
    trainRMSE[iter] <- RMSE(train, est_rating)
    testRMSE[iter] <- RMSE(test, est_rating)
    
    E = Sys.time()
    
    cat("Iter", iter, "  RMSE for train set:", round(trainRMSE[iter], 4), "  RMSE for test set:", round(testRMSE[iter], 4), "  Time cost:", round(E-S, 2), "s\n")
    
    iter <- iter + 1
  }
  # Result
  ratings_est <- est_rating
  return(list("User" = Users, 
              "Movie" = Movies, 
              "Rating" = ratings_est, 
              "Train RMSE" = trainRMSE, 
              "Test RMSE" = testRMSE) 
         )
}
```

```{r}
result = ALS.R1R3(f = 10, lambda = 5, beta = 0.4, maxIters = 20 , data = data,
            train = data_train, test = data_test)
```

```{r}
save(result, file = '../output/resultR1R3.Rdata')
```










